stages:
  - build

variables:
  DOCKERHUB_IMAGE: "daffamusyafa/english-learner-backend"

build_and_push_to_dockerhub:
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
    
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    # Kita tidak perlu $VERSION_TAG di sini, kita akan pakai $CI_COMMIT_TAG

  script:
    - echo "Logging in to Docker Hub..."
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    
    # $CI_COMMIT_TAG akan berisi nama tag yang Anda push (misal: "v1.1")
    - echo "Building image with tag: $CI_COMMIT_TAG"
    - docker build -t $DOCKERHUB_IMAGE:$CI_COMMIT_TAG .
    
    - echo "Creating 'latest' tag..."
    - docker tag $DOCKERHUB_IMAGE:$CI_COMMIT_TAG $DOCKERHUB_IMAGE:latest
    
    - echo "Pushing image to Docker Hub..."
    - docker push $DOCKERHUB_IMAGE:$CI_COMMIT_TAG
    - docker push $DOCKERHUB_IMAGE:latest
    
  # ▼ PENTING: Mengubah aturan 'only'
  # Job ini TIDAK akan berjalan di branch 'master'
  # Job ini HANYA akan berjalan jika Anda me-push 'tag'
  only:
    - tags